# Maven
# Build your Java project and run tests with Apache Maven.
# Deploy
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
   - name: process.clean
     value: false

pool: 'my-personal-computer'
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build Maven Project
    steps:
      # Prepare Analysis Configuration task
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar-connection'
        scannerMode: 'Other'
        extraProperties: 'sonar.projectKey=sqa_3af383bd7dedff2416e3013e85c5bdc70c83b8dd'
    # Publish Quality Gate Result task
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'
    - task: Maven@3
      #env:
      #  JAVA_HOME: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: SampleSpringBootBuild
